name: spinningup
channels:
  - defaults
dependencies:
  - astroid=2.0.4
  - ca-certificates=2018.03.07
  - certifi=2018.10.15
  - isort=4.3.4
  - lazy-object-proxy=1.3.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libstdcxx-ng=8.2.0
  - mccabe=0.6.1
  - ncurses=6.1
  - openssl=1.1.1
  - pip=18.1
  - pylint=2.1.1
  - python=3.6.7
  - readline=7.0
  - rope=0.14.0
  - setuptools=40.6.2
  - six=1.11.0
  - sqlite=3.25.3
  - tk=8.6.8
  - typed-ast=1.1.0
  - wheel=0.32.2
  - wrapt=1.10.11
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - absl-py==0.6.1
    - astor==0.7.1
    - atari-py==0.1.7
    - atomicwrites==1.2.1
    - attrs==18.2.0
    - backcall==0.1.0
    - box2d-py==2.3.8
    - cffi==1.12.2
    - chardet==3.0.4
    - cloudpickle==0.5.2
    - cycler==0.10.0
    - cython==0.29.5
    - decorator==4.3.0
    - future==0.17.1
    - gast==0.2.0
    - glfw==1.7.1
    - grpcio==1.16.1
    - gym==0.10.9
    - h5py==2.8.0
    - idna==2.7
    - imageio==2.5.0
    - ipython==7.1.1
    - ipython-genutils==0.2.0
    - jedi==0.13.1
    - joblib==0.13.0
    - keras-applications==1.0.6
    - keras-preprocessing==1.0.5
    - kiwisolver==1.0.1
    - lockfile==0.12.2
    - markdown==3.0.1
    - matplotlib==3.0.2
    - more-itertools==4.3.0
    - mpi4py==3.0.0
    - mujoco-py==1.50.1.68
    - numpy==1.15.4
    - pandas==0.23.4
    - parso==0.3.1
    - pexpect==4.6.0
    - pickleshare==0.7.5
    - pillow==5.3.0
    - pluggy==0.8.0
    - prompt-toolkit==2.0.7
    - protobuf==3.6.1
    - psutil==5.4.8
    - ptyprocess==0.6.0
    - py==1.7.0
    - pycparser==2.19
    - pyglet==1.3.2
    - pygments==2.2.0
    - pyopengl==3.1.0
    - pyparsing==2.3.0
    - pytest==4.0.0
    - python-dateutil==2.7.5
    - pytz==2018.7
    - requests==2.20.1
    - scipy==1.1.0
    - seaborn==0.8.1
    - spinup==0.1.1
    - tensorboard==1.12.0
    - tensorflow==1.12.0
    - termcolor==1.1.0
    - tqdm==4.28.1
    - traitlets==4.3.2
    - urllib3==1.24.1
    - wcwidth==0.1.7
    - werkzeug==0.14.1

